nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/plugin-list.cjs
    # Edited version of:
    # spec: "https://github.com/arendjr/yarn-plugin-list/releases/latest/download/yarn-plugin-list.js"
