<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>cpp2</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function-definition</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type-name</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>punctuation-comma</key>
      <dict>
        <key>name</key>
        <string>punctuation.separator.comma.cpp2</string>
        <key>match</key>
        <string>,</string>
      </dict>
      <key>punctuation-colon</key>
      <dict>
        <key>name</key>
        <string>punctuation.separator.colon.cpp2</string>
        <key>match</key>
        <string>:[^:]</string>
      </dict>
      <key>definition</key>
      <dict>
        <key>name</key>
        <string>meta.definition.cpp2</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#function-definition</string>
          </dict>
        </array>
      </dict>
      <key>function-definition</key>
      <dict>
        <key>name</key>
        <string>meta.definition.function.cpp2</string>
        <key>begin</key>
        <string>(?x)
([_[:alpha:]][_[:alnum:]]*)\s*
(:[^:])\s*
</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.cpp2</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.colon.cpp2</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=[\}\;])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#function-type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#in-brackets-function-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#single-expression-function-assignment</string>
          </dict>
        </array>
      </dict>
      <key>single-expression-function-assignment</key>
      <dict>
        <key>name</key>
        <string>meta.function.body.cpp2</string>
        <key>begin</key>
        <string>(?x)
(=)\s*
</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.cpp2</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.statement.cpp2</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#function-content</string>
          </dict>
        </array>
      </dict>
      <key>in-brackets-function-assignment</key>
      <dict>
        <key>name</key>
        <string>meta.function.body.cpp2</string>
        <key>begin</key>
        <string>(?x)
(=)\s*
(\{)
</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.cpp2</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.curlybrace.open.cpp2</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.curlybrace.close.cpp2</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#function-content</string>
          </dict>
        </array>
      </dict>
      <key>function-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
        </array>
      </dict>
      <key>type</key>
      <dict>
        <key>name</key>
        <string>meta.type.cpp2</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#function-type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-name</string>
          </dict>
        </array>
      </dict>
      <key>type-name</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([_[:alpha:]][_[:alnum:]]*)\s*(::)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.namespace.cpp2</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.static-accessor.cpp2</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(::)\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.static-accessor.cpp2</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.cpp2</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.cpp2</string>
            <key>match</key>
            <string>[_[:alpha:]][_[:alnum:]]*</string>
          </dict>
        </array>
      </dict>
      <key>function-return-type-seperator</key>
      <dict>
        <key>name</key>
        <string>punctuation.separator.function-return-type.cpp2</string>
        <key>match</key>
        <string>-&gt;</string>
      </dict>
      <key>function-type</key>
      <dict>
        <key>name</key>
        <string>meta.function-type.cpp2</string>
        <key>begin</key>
        <string>(?x)
(?=\()
</string>
        <key>end</key>
        <string>(?=[=;])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#parenthesized-parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-return-type-seperator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
        </array>
      </dict>
      <key>parameter-modifier</key>
      <dict>
        <key>name</key>
        <string>storage.modifier.cpp2</string>
        <key>match</key>
        <string>\b(in|out|inout|copy|move|forward)\b</string>
      </dict>
      <key>parameter-name</key>
      <dict>
        <key>match</key>
        <string>(?x)
([_[:alpha:]][_[:alnum:]]*)
</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.parameter.cpp2</string>
          </dict>
        </dict>
      </dict>
      <key>parameter</key>
      <dict>
        <key>name</key>
        <string>meta.parameter.cpp2</string>
        <key>begin</key>
        <string>(?x)
(?:(\w+)?\s+)?
([_[:alpha:]][_[:alnum:]]*)\s*
(:)\s*
</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameter-modifier</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameter-name</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.colon.cpp2</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[\)\,])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-name</string>
          </dict>
        </array>
      </dict>
      <key>parenthesized-parameters</key>
      <dict>
        <key>name</key>
        <string>meta.function.parameters.cpp2</string>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.begin.cpp2</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.parameters.end.cpp2</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parameter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.cpp2</string>
            <key>begin</key>
            <string>/\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.cpp2</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.cpp2</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^\s+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.cpp2</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.block.documentation.cpp2</string>
                <key>begin</key>
                <string>(?&lt;!/)///(?!/)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.cpp2</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=$)</string>
              </dict>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.cpp2</string>
                <key>begin</key>
                <string>(?&lt;!/)//(?:(?!/)|(?=//))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.cpp2</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=$)</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.cpp2</string>
  </dict>
</plist>